name: Backend CI

on:
  push:
    branches:
      - main
      - docker-main
  pull_request:
    branches:
      - main
      - docker-main

jobs:
  backend-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # Install system dependencies
      - name: Install system dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y portaudio19-dev build-essential libssl-dev
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew update
            brew install portaudio pkg-config ffmpeg
            xcode-select --install || echo "Xcode CLT already installed"
          fi

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Lint & Format Check
      - name: Lint & Format Check
        run: |
          python -m pip install flake8 black autoflake
          flake8 backend/ --max-line-length=120 --exit-zero
          black --check backend/ || echo "Run 'black backend/' to fix formatting"
          autoflake --check --remove-unused-variables --remove-all-unused-imports -r backend/ || echo "Unused imports found"

      # Optional: Auto-fix formatting
      - name: Auto-fix formatting
        if: github.event_name == 'push'
        run: |
          black backend/
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r backend/

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/imjusthenry/droneworld/backend:latest ./backend

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/imjusthenry/droneworld/backend:latest
