name: Backend CI

on:
  push:
    branches:
      - main
      - docker-main
  pull_request:
    branches:
      - main
      - docker-main

jobs:
  backend-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]          # Use Linux for Docker builds
        python-version: ["3.10"]     # Python version for the backend

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"  # Cache pip dependencies

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev build-essential libssl-dev

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Lint & Format Check
      - name: Lint & Format Check
        run: |
          python -m pip install flake8 black
          # Lint backend files, allow slightly longer lines
          flake8 backend/ --max-line-length=120 --exit-zero
          # Check formatting with black
          black --check backend/ || echo "Run 'black backend/' to fix formatting"

      # Optional: auto-fix linting issues
      - name: Auto-fix formatting
        if: github.event_name == 'push'
        run: |
          black backend/
          # Remove unused imports automatically
          pip install autoflake
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r backend/

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/ImJustHenry/DroneWorld/backend:latest ./backend

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/ImJustHenry/DroneWorld/backend:latest
