name: Frontend CI

on:
  push:
    branches:
      - main
      - docker-main
  pull_request:
    branches:
      - main
      - docker-main

jobs:
  frontend-setup:
    runs-on: ubuntu-latest  # Docker builds run best on Linux

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Install dependencies & build
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # Lint & format (optional)
      - name: Lint frontend
        run: |
          cd frontend
          npm install -g eslint prettier
          npx eslint src --ext .js,.jsx,.ts,.tsx,.json
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/ImJustHenry/DroneWorld/frontend:latest ./frontend

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/ImJustHenry/DroneWorld/frontend:latest
